version: '3.8'

services:
  web:
    build: ./CarDealerWeb-Django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./CarDealerWeb-Django:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - network1
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=khiem123
      - POSTGRES_DB=cardealer_db
    networks:
      - network1
volumes:
  postgres_data:
networks:
  network1: